version: '2'
services:
  db:
    image: postgres:12.1
    volumes:
      - "./postgres-data:/var/lib/postgresql/data:delegated"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
#  adminer:
#    image: adminer:latest
#    restart: unless-stopped
#    ports:
#      - 8081:8080
#    depends_on:
#      - db